In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   title                 4803 non-null   object
 2   genres                4803 non-null   object
 3   keywords              4803 non-null   object
 4   overview              4800 non-null   object
 5   production_companies  4803 non-null   object
 6   tagline               3959 non-null   object
 7   cast                  4803 non-null   object
 8   crew                  4803 non-null   object
dtypes: int64(1), object(8)
memory usage: 337.8+ KB

In [4]:
df.fillna("",inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   title                 4803 non-null   object
 2   genres                4803 non-null   object
 3   keywords              4803 non-null   object
 4   overview              4803 non-null   object
 5   production_companies  4803 non-null   object
 6   tagline               4803 non-null   object
 7   cast                  4803 non-null   object
 8   crew                  4803 non-null   object
dtypes: int64(1), object(8)
memory usage: 337.8+ KB

In [6]:
df.loc[0,'genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [7]:
import ast 
def get_names(text):
    y = ast.literal_eval(text)
    words = []
    for a in y:
        words.append(a['name'].replace(' ','-'))
    text = ',' .join(words).lower()
    return text

In [8]:
df['genres'] = df['genres'].apply(get_names)
df['keywords'] = df['keywords'].apply(get_names)
df['production_companies'] = df['production_companies'].apply(get_names)
df['cast'] = df['cast'].apply(get_names)
df['crew'] = df['crew'].apply(get_names)

In [9]:
df

,id,title,genres,keywords,overview,production_companies,tagline,cast,crew
0,19995,Avatar,"action,adventure,fantasy,science-fiction","culture-clash,future,space-war,space-colony,so...","In the 22nd century, a paraplegic Marine is di...","ingenious-film-partners,twentieth-century-fox-...",Enter the World of Pandora.,"sam-worthington,zoe-saldana,sigourney-weaver,s...","stephen-e.-rivkin,rick-carter,christopher-boye..."
1,285,Pirates of the Caribbean: At World's End,"adventure,fantasy,action","ocean,drug-abuse,exotic-island,east-india-trad...","Captain Barbossa, long believed to be dead, ha...","walt-disney-pictures,jerry-bruckheimer-films,s...","At the end of the world, the adventure begins.","johnny-depp,orlando-bloom,keira-knightley,stel...","dariusz-wolski,gore-verbinski,jerry-bruckheime..."
2,206647,Spectre,"action,adventure,crime","spy,based-on-novel,secret-agent,sequel,mi6,bri...",A cryptic message from Bond’s past sends him o...,"columbia-pictures,danjaq,b24",A Plan No One Escapes,"daniel-craig,christoph-waltz,léa-seydoux,ralph...","thomas-newman,sam-mendes,anna-pinnock,john-log..."
3,49026,The Dark Knight Rises,"action,crime,drama,thriller","dc-comics,crime-fighter,terrorist,secret-ident...",Following the death of District Attorney Harve...,"legendary-pictures,warner-bros.,dc-entertainme...",The Legend Ends,"christian-bale,michael-caine,gary-oldman,anne-...","hans-zimmer,charles-roven,christopher-nolan,ch..."
4,49529,John Carter,"action,adventure,science-fiction","based-on-novel,mars,medallion,space-travel,pri...","John Carter is a war-weary, former military ca...",walt-disney-pictures,"Lost in our world, found in another.","taylor-kitsch,lynn-collins,samantha-morton,wil...","andrew-stanton,andrew-stanton,john-lasseter,co..."
...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,"action,crime,thriller","united-states–mexico-barrier,legs,arms,paper-k...",El Mariachi just wants to play his guitar and ...,columbia-pictures,"He didn't come looking for trouble, but troubl...","carlos-gallardo,jaime-de-hoyos,peter-marquardt...","robert-rodriguez,robert-rodriguez,robert-rodri..."
4799,72766,Newlyweds,"comedy,romance",,A newlywed couple's honeymoon is upended by th...,,A newlywed couple's honeymoon is upended by th...,"edward-burns,kerry-bishé,marsha-dietlein,caitl...","edward-burns,edward-burns,edward-burns,william..."
4800,231617,"Signed, Sealed, Delivered","comedy,drama,romance,tv-movie","date,love-at-first-sight,narration,investigati...","""Signed, Sealed, Delivered"" introduces a dedic...","front-street-pictures,muse-entertainment-enter...",,"eric-mabius,kristin-booth,crystal-lowe,geoff-g...","carla-hetland,harvey-kahn,adam-sliwinski,marth..."
4801,126186,Shanghai Calling,,,When ambitious New York attorney Sam is sent t...,,A New Yorker in Shanghai,"daniel-henney,eliza-coupe,bill-paxton,alan-ruc...","daniel-hsia,daniel-hsia"
4802,25975,My Date with Drew,documentary,"obsession,camcorder,crush,dream-girl",Ever since the second grade when he first saw ...,"rusty-bear-entertainment,lucky-crow-films",,"drew-barrymore,brian-herzlinger,corey-feldman,...","clark-peterson,andrew-reimer,brian-herzlinger,..."

In [10]:
from nlp_functions import nlp_pipeline
df['overview'] = nlp_pipeline(df['overview'])
df['tagline'] = nlp_pipeline(df['tagline'])

In [11]:
df['overview'] = df['overview'].str.replace(' ', ',')
df['tagline'] = df['tagline'].str.replace(' ', ',')

In [12]:
df['tags'] = df['genres'] + ',' + df['keywords'] + ',' + df['overview'] + ',' + df['production_companies'] + ',' + df['tagline'] + ',' + df['cast'] + ',' + df['crew']

In [13]:
df = df[['id','title','tags']]

In [14]:
df

,id,title,tags
0,19995,Avatar,"action,adventure,fantasy,science-fiction,cultu..."
1,285,Pirates of the Caribbean: At World's End,"adventure,fantasy,action,ocean,drug-abuse,exot..."
2,206647,Spectre,"action,adventure,crime,spy,based-on-novel,secr..."
3,49026,The Dark Knight Rises,"action,crime,drama,thriller,dc-comics,crime-fi..."
4,49529,John Carter,"action,adventure,science-fiction,based-on-nove..."
...,...,...,...
4798,9367,El Mariachi,"action,crime,thriller,united-states–mexico-bar..."
4799,72766,Newlyweds,"comedy,romance,,newlywed,couple,honeymoon,upen..."
4800,231617,"Signed, Sealed, Delivered","comedy,drama,romance,tv-movie,date,love-at-fir..."
4801,126186,Shanghai Calling,",,ambitious,new,york,attorney,sam,send,shangha..."
4802,25975,My Date with Drew,"documentary,obsession,camcorder,crush,dream-gi..."

In [15]:
df.loc[0,'tags']

"action,adventure,fantasy,science-fiction,culture-clash,future,space-war,space-colony,society,space-travel,futuristic,romance,space,alien,tribe,alien-planet,cgi,marine,soldier,battle,love-affair,anti-war,power-relations,mind-and-soul,3d,22nd,century,paraplegic,marine,dispatch,moon,pandora,unique,mission,tear,follow,order,protect,alien,civilization,ingenious-film-partners,twentieth-century-fox-film-corporation,dune-entertainment,lightstorm-entertainment,enter,world,pandora,sam-worthington,zoe-saldana,sigourney-weaver,stephen-lang,michelle-rodriguez,giovanni-ribisi,joel-david-moore,cch-pounder,wes-studi,laz-alonso,dileep-rao,matt-gerald,sean-anthony-moran,jason-whyte,scott-lawrence,kelly-kilgour,james-patrick-pitt,sean-patrick-murphy,peter-dillon,kevin-dorman,kelson-henderson,david-van-horn,jacob-tomuri,michael-blain-rozgay,jon-curry,luke-hawker,woody-schultz,peter-mensah,sonia-yee,jahnel-curfman,ilram-choi,kyla-warren,lisa-roumain,debra-wilson,chris-mala,taylor-kibby,jodie-landau,julie-lamm,cullen-b.-madden,joseph-brady-madden,frankie-torres,austin-wilson,sara-wilson,tamica-washington-miller,lucy-briant,nathan-meister,gerry-blair,matthew-chamberlain,paul-yates,wray-wilson,james-gaylyn,melvin-leno-clark-iii,carvon-futrell,brandon-jelkes,micah-moch,hanniyah-muhammad,christopher-nolen,christa-oliver,april-marie-thomas,bravita-a.-threatt,colin-bleasdale,mike-bodnar,matt-clayton,nicole-dionne,jamie-harrison,allan-henry,anthony-ingruber,ashley-jeffery,dean-knowsley,joseph-mika-hunt,terry-notary,kai-pantano,logan-pithyou,stuart-pollock,raja,gareth-ruck,rhian-sheehan,t.-j.-storm,jodie-taylor,alicia-vela-bailey,richard-whiteside,nikie-zambo,julene-renee,stephen-e.-rivkin,rick-carter,christopher-boyes,christopher-boyes,mali-finn,james-horner,james-cameron,james-cameron,james-cameron,james-cameron,james-cameron,andrew-menzies,jill-brooks,margery-simkin,kevin-ishioka,dick-bernstein,shannon-mills,dennie-thorpe,jana-vance,deborah-lynn-scott,jon-landau,sean-haworth,kim-sinclair,kim-sinclair,richard-f.-mays,laeta-kalogridis,mayes-c.-rubeo,mauro-fiore,scott-herbertson,woody-schultz,linda-devetta,linda-devetta,richard-bluck,simon-bright,richard-martin,steve-r.-moore,john-refoua,karl-j.-martin,chiling-lin,ilram-choi,steven-quale,carla-meyer,nick-bassett,jill-cormack,andy-mclaren,terry-notary,garrett-warren,jonathan-rothbart,stefan-dechant,todd-cherniawsky,miranda-rivers,robert-stromberg,john-harding,roberto-de-angelis,mike-smithson,alain-lalanne,lucas-salton,janace-tashjian,stephen-rosenbaum,frankie-karena,lisa-lovaas,jonathan-fawkner,robert-bavin,anthony-almaraz,carolyn-m.-fenton,beth-koenigsberg,sam-page,tex-kadonaga,kim-foscato,tammy-s.-lee,denny-caira,james-waitkus,addison-teague,c.-scott-baker,luke-caska,david-chow,jonathan-dyer,joseph-hiura,rebecca-jellie,robert-andrew-johnson,mike-stassi,john-villarino,jeffrey-wisniewski,cheryl-nardi,marshall-winn,gwendolyn-yates-whittle,william-stein,lula-washington,chris-del-conte,r.-christopher-white,dan-lemmon,tim-nielsen,michael-mulholland,thomas-nittmann,edson-williams,christine-carr,john-bruno,david-emmerichs,christopher-scarabosio,jennifer-teves,brigitte-yorke,ken-fischer,iain-hutton,steve-ingram,joyce-cox,jenny-foster,christopher-marino,jim-milton,cyndi-ochs,lucas-putnam,anthony-'max'-ivins,john-knoll,eric-saindon,wayne-stables,david-stinnett,guy-williams,stuart-thorp,giles-coburn,mark-fellman,scott-sprague,jeremy-hollobon,orlando-meunier,taisuke-tanimura,lilia-mishel-acevedo,alejandro-m.-hernandez,marvin-hall,judy-alley,mike-perry,andrew-morley,seth-engstrom,eric-oliver,matsune-suzuki,paul-tobin,roxane-griffin,arun-ram-mohan,georgia-lockhart-adams,thrain-shadbolt,brad-alexander,shadi-almassizadeh,simon-clutterbuck,graeme-demmocks,adrian-fernandes,mitch-gates,jerry-kung,andy-lomas,sebastian-marino,matthias-menz,sergei-nevshupov,philippe-rebours,michael-takarangi,david-weitzberg,ben-white,min-windle"

In [16]:
def get_unique_values(text):
    return ','.join(list(set(text.split(','))))
for i in df.index:
    df.loc[i, 'tags'] = get_unique_values(df.loc[i, 'tags'])

In [17]:
df.to_csv("final_data.csv", index = False)